spring.application.name=quizapp

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://quizapp-shanksredhaired2026-7688.e.aivencloud.com:28233/defaultdb?sslmode=require}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASS:AVNS_wVo-h35UuYr_GNVQf4q}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0
server.port=8080
